version: "3.7"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3000:80"
    networks:
      - socketCuster

  socket1:
    build: .
    restart: on-failure
    ports:
      - 4555
    networks:
      - socketCuster

  socket2:
    build: .
    restart: on-failure
    ports:
      - 4555
    networks:
      - socketCuster

  socket3:
    build: .
    restart: on-failure
    ports:
      - 4555
    networks:
      - socketCuster

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - socketCuster

networks:
  socketCuster:
    driver: bridge
